export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOOUT_USER = 'LOGOOUT_USER';

export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_BY_ARRIVA = 'GET_PRODUCTS_BY_ARRIVA';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_WOODS = 'GET_WOODS';
export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';